kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: python-k8s-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: wms-eduard
roleRef:
  kind: ClusterRole
  name: python-k8s-controller
  apiGroup: rbac.authorization.k8s.io