kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: python-k8s-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["list", "watch", "patch", "create", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "patch"]