apiVersion: batch/v1
kind: Job
metadata:
  name: download-dwd-data-job
spec:
  template:
    spec:
      volumes:
        # Volumes have a name and configuration based on the type of volume.
        # In this example, we use the emptyDir volume type
        - name: dwd-grib-data
          persistentVolumeClaim:
            claimName: dwd-grib-data-claim
      containers:
      - name: dwd-open-data-downloader
        image: eduardrosert/dwd-open-data-downloader
        volumeMounts:
          - name: dwd-grib-data # This is the name of the volume we set at the pod level
            mountPath: /dwd-grib-data # Where to mount this directory in our container
        command: ["python", "/opendata-downloader.py", "--model", "icon-eu", "--single-level-fields", "t_2m", "-v", "--directory", "/dwd-grib-data"]
      restartPolicy: Never
  backoffLimit: 4