apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-dwd-skinnywms-demo-claim
spec:
  storageClassName: rook-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
