apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwd-grib-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dwd-grib-data"