apiVersion: v1
kind: Service
metadata:
  labels:
    app: skinnywms-demo
  name: skinnywms-demo
spec:
  ports:
  - nodePort: 31090
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: skinnywms-demo
  type: NodePort