apiVersion: autoscaling/v1
#apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: skinnywms-demo
  namespace: wms-eduard
spec:
  maxReplicas: 50
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: skinnywms-demo
  targetCPUUtilizationPercentage: 75
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
